name: Project Wallace CSS Analytics
description: Report CSS analytics for every Pull Request
author: 'Bart Veneman (ProjectWallace.com)'

inputs:
  github-token:
    required: true
  css-path:
    description: 'Path to the CSS you want analyzed'
    required: true
  post-pr-comment:
    description: Whether this action should post a comment to the PR with analytics
    required: true
    default: true

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  color: 'blue'
  icon: 'bar-chart-2'
